# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, and sign the desktop application
# built on .NET Core.

name: .NET Core Desktop

on:
  push:
<<<<<<< HEAD
    branches: [ "cnorton/saveable" ]
  pull_request:
    branches: [ "cnorton/saveable" ]
||||||| 98a1c9b
=======
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
>>>>>>> main

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: GoDoIt.sln    
      Test_Project_Path: GoDoIt.Tests\GoDoIt.Tests.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: dotnet restore $env:Solution_Name

    # Builds the application
    - name: Build the application
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }} --no-restore
      
    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test $env:Test_Project_Path --no-build
